name: Run Pytest

on:
  push:
    branches: [ ci-cd ]
  pull_request:
    branches: [ ci-cd ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Set up Conda
      uses: conda-incubator/setup-miniconda@v2
      with:
        auto-activate-base: false
        activate-environment: gt
        environment-file: none
        miniforge-variant: Mambaforge
        miniforge-version: latest

    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y cmake g++ libomp-dev

    - name: Init submodules
      run: |
        git submodule update --init --recursive

    - name: Set up graph-tool environment using install.sh
      shell: bash -l {0}
      run: |
        chmod +x install.sh
        ./install.sh

    - name: Build RECCS
      shell: bash -l {0}
      run: |
        mkdir -p build
        cd build
        cmake ..
        make

    - name: List all files
      shell: bash -l {0}
      run: ls -R

    - name: Run tests with pytest in gt environment
      shell: bash -l {0}
      run: |
        conda activate gt
        pytest test/ --tb=short --disable-warnings
